sudo: required
services:
    - docker

script:
    - docker build -t yarinif/node .
    - docker images yarinif/node

before_deploy:
    - docker login -u "yifrach" -p "205697410Yi"

deploy:
    provider: script
    script: docker push yarinif/node
    on:
        branch: master
